#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/common
#
common_packages:
  - git
  - curl
  - wget
  - vim
  - tree
  - unzip
  - zip
  - htop
  - net-tools
  - python3-pip
  - chrony

chrony_service: chrony

chrony_package: chrony
