---
all:
  children:

    webservers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
        web02:
          ansible_host: 10.0.1.11

    dbservers:
      hosts:
        db01:
          ansible_host: 10.0.2.10

  vars:
    ansible_user: ubuntu
